### ISSUE TITLE
No module named "onewire" error when using DS18x20 temperature block

### ISSUE THREAD

**Issue by reneenoble** [kookaberry/kooka-releases#1]
Running Kookaberry Blockly v1.6 on Mac OS Big Sur

Received the following error: 
![Screen Shot 2021-02-05 at 1 55 53 pm](https://user-images.githubusercontent.com/7269759/106983446-06c3b800-67ba-11eb-95bb-f1bd16cc77e3.png)

Code that caused it to happen is as follows:
![Screen Shot 2021-02-05 at 1 55 57 pm](https://user-images.githubusercontent.com/7269759/106983455-09bea880-67ba-11eb-9a81-6fbe7f4ca639.png)

Script for "show script" button in case it is of use:
```import machine
import kooka
import fonts
import time
from machine import Pin

start_time = None
running = None

def onewire_ds18_read_temp(p):
    import onewire, ds18x20
    ds = ds18x20.DS18X20(onewire.OneWire(Pin(p, Pin.PULL_UP)))
    roms = ds.scan()
    if not roms: return -100
    ds.convert_temp()
    time.sleep(0.75)
    return ds.read_temp(roms[0])


while True:
    if kooka.button_a.was_pressed():
        kooka.display.setfont(fonts.mono8x13)
        start_time = time.time()
        if kooka.button_a.is_pressed():
            running = True
        while running:
            kooka.display.fill(0)
            kooka.display.print(onewire_ds18_read_temp("P1"), show=0)
            kooka.display.show()
    kooka.display.show()
    machine.idle()

```

**Comment by dpgeorge** [comment]
You'll need to install the onewire and ds18x20 modules to the Kookaberry.

Steps to do that:
- download `onewire.mpy` and `ds18x20.mpy` from this repository, from the lib/ directory: https://github.com/kookaberry/kooka-releases/tree/master/lib
- make sure you can see the Kookaberry USB mass storage drive
- make a directory called "lib" in the Kookaberry USB mass storage drive if it doesn't already exist
- copy the mpy files from above to the lib directory on the Kookaberry

**Comment by reneenoble** [comment]
Thanks, I'll do that!
